services:
  ansible:
    build: .
    image: ansible:latest
    container_name: ansible
    stdin_open: true
    tty: true
    volumes:
      - ./playbooks:/ansible/playbooks
      - ./inventory:/ansible/inventory
      - ./roles:/ansible/roles
      - ./group_vars:/ansible/group_vars
      - ./host_vars:/ansible/host_vars
      - ./AcessoDesenvolvedor.pem:/root/.ssh/AcessoDesenvolvedor.pem
      - ./ansible.cfg:/ansible/ansible.cfg:ro
    working_dir: /ansible
